person:
    represented_as: node
    label_in_input: person

male:
    represented_as: node
    label_in_input: male

female:
    represented_as: node
    label_in_input: female

parent:
    represented_as: node
    label_in_input: parent

isRelative:
    represented_as: edge
    label_in_input: isRelative
    source: person
    target: person

childOf:
    represented_as: edge
    label_in_input: childOf
    source: person
    target: person

parentOf:
    represented_as: edge
    label_in_input: parentOf
    source: person
    target: person

