biocypher:
    debug: true
    offline: true
    dbms: owl

    # Ontology configuration
    head_ontology:
        url: input/dataproperties_class/ontology.ttl
        root_node: Biocypherroot

owl:
    edge_model: ObjectProperty
    file_format: turtle
    labels_order: "Ascending" # Default: From more specific to more generic.
    node_labels_order: "None" # Default: use labels_order.
    edge_labels_order: "None"
