person:
    represented_as: node
    label_in_input: person
    properties:
        - first_name: str
        - last_name: str
        - age: str
        - rents_home: bool
        - possess_home: bool

is_relative:
    represented_as: edge
    label_in_input: is_relative
    source: person
    target: person

child_of:
    represented_as: edge
    label_in_input: child_of
    source: person
    target: person

parent_of:
    represented_as: edge
    label_in_input: parent_of
    source: person
    target: person

has_pet:
    represented_as: edge
    label_in_input: has_pet
    source: person
    target: animal

