biocypher:
    debug: true
    offline: true
    dbms: owl

    # Ontology configuration
    head_ontology:
        url: graphGeneration/input/simplest/ontology.ttl
        root_node: Biocypherroot

owl:
    edge_model: ObjectProperty
    file_format: turtle
