person:
    represented_as: node
    label_in_input: person

parent:
    represented_as:
    label_in_input: parent

childOf:
    represented_as: edge
    label_in_input: childOf
    source: person
    target: person

parentOf:
    represented_as: edge
    label_in_input: parentOf
    source: person
    target: person

