biocypher:
    debug: true
    offline: true
    dbms: biopathnet

    # Ontology configuration
    head_ontology:
        url: output/relatives_has_role/reasoned.ttl
        root_node: Biocypherroot

