biocypher:
    debug: true
    offline: true
    dbms: owl

    # Ontology configuration
    head_ontology:
        url: input/relatives/relatives_input_ontology.ttl
        root_node: Biocypherroot

owl:
    edge_model: ObjectProperty
    file_format: turtle
